language: rust
rust:
  - stable
  - beta
  - nightly
 

before_script:
  - rustup component add clippy
  

script:
  # if you want the build job to fail when encountering warnings, use
  # - cargo clippy -- -D warnings
  # in order to also check tests and non-default crate features, use
  - cargo clippy --all-targets --all-features
  - cargo build
  - cargo build --release
  - cargo test

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta # clippy currently has a bug on beta
  fast_finish: true
