version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2019

configuration: Release

install:
    - set QTDIR=C:\Qt\5.14.2\mingw73_64
    - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%;
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;C:\cargo\bin
    - rustc -Vv
    - cargo -V

before_build:
    - cargo test
    - cd gui
    - cmake
    - make

build_script:
    - mingw32-make

