environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
    CRATE_NAME: cryptyrust
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\cargo\bin
  - rustc -Vv
  - cargo -V

build: false
test_script:
  - cargo test --target %TARGET% --verbose

after_test:
  # Generate artifacts for release
  - cargo build --release --verbose
  - mkdir staging
  # TODO update this part to copy the artifacts that make sense for your project
  - copy target\release\cryptyrust_cli.exe staging
  - cd staging
    # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%CRATE_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%CRATE_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip
  
