version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2019

configuration: Release

environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
    CRATE_NAME: cryptyrust
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"

install:
    - set QTDIR=C:\Qt\6.0.1\mingw81_64
    - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%;
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;C:\cargo\bin
    - rustc -Vv
    - cargo -V

build_script:
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - cargo test
    - dir
    - cd gui
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - dir
    - make
