version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2019

configuration: Release

environment:
  global:
    TARGET: x86_64-pc-windows-msvc
    RUST_VERSION: stable
    CRATE_NAME: cryptyrust
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"

install:
    - set QTDIR=C:\Qt\5.15.2\msvc2019_64
    - set PATH=%PATH%;%QTDIR%\bin
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;C:\cargo\bin
    - rustc -Vv
    - cargo -V

build_script:
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - cargo test
    - cargo build --release
    - dir
    - cd gui
    - mkdir build
    - cd build
    - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - dir
    - nmake
    - cd %APPVEYOR_BUILD_FOLDER%
    - dir
    - mkdir cryptyrust_win_x64
    - cd cryptyrust_win_x64
    - xcopy %APPVEYOR_BUILD_FOLDER%\target\release\cryptyrust_cli.exe %APPVEYOR_BUILD_FOLDER%\cryptyrust_win_x64\
    - xcopy %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\cryptyrust_win_x64\
    - xcopy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\cryptyrust_win_x64\
    - xcopy %APPVEYOR_BUILD_FOLDER%\gui\build\cryptyrust.exe %APPVEYOR_BUILD_FOLDER%\cryptyrust_win_x64\
    - windeployqt --release --no-translations --no-opengl-sw cryptyrust.exe
    
artifacts:
    - path: cryptyrust_win_x64
      type: zip
