use base64ct::{Base64, Encoding};
use std::fs::File;
use std::io::{self, BufRead, Read, Write};
use std::path::Path;

pub const PEM_LABEL: &str = "CRYPTYRUST ENCRYPTED DATA";

// 48 input bytes → exactly 64 base64 chars (multiple of 3 → no mid-stream padding)
const BYTES_PER_LINE: usize = 48;
const LINE_WIDTH: usize = 64; // = BYTES_PER_LINE * 4 / 3

// ── Writer ────────────────────────────────────────────────────────────────────

/// Streams base64-encoded PEM output with zero heap allocation per line.
/// Uses a 64 KB BufWriter to minimize write syscalls.
pub struct PemWriter {
    inner: io::BufWriter<File>,
    buf: Vec<u8>,
}

impl PemWriter {
    pub fn new(inner: File, version: &str) -> io::Result<Self> {
        let mut bw = io::BufWriter::with_capacity(64 * 1024, inner);
        writeln!(bw, "# Generated by Cryptyrust v{}", version)?;
        writeln!(bw, "-----BEGIN {}-----", PEM_LABEL)?;
        Ok(Self {
            inner: bw,
            buf: Vec::with_capacity(BYTES_PER_LINE * 2),
        })
    }

    pub fn finish(mut self) -> io::Result<File> {
        if !self.buf.is_empty() {
            // Remaining bytes need base64 padding — max 64 output chars
            let mut out = [0u8; LINE_WIDTH];
            let encoded = Base64::encode(&self.buf, &mut out)
                .map_err(|_| io::Error::other("base64 encode"))?;
            self.inner.write_all(encoded.as_bytes())?;
            self.inner.write_all(b"\n")?;
        }
        writeln!(self.inner, "-----END {}-----", PEM_LABEL)?;
        self.inner.flush()?;
        self.inner.into_inner().map_err(Into::into)
    }
}

impl Write for PemWriter {
    fn write(&mut self, data: &[u8]) -> io::Result<usize> {
        self.buf.extend_from_slice(data);

        let complete = (self.buf.len() / BYTES_PER_LINE) * BYTES_PER_LINE;
        if complete > 0 {
            // Stack-allocated line buffer: 64 base64 chars + newline
            let mut line_buf = [0u8; LINE_WIDTH + 1];
            line_buf[LINE_WIDTH] = b'\n';

            for chunk in self.buf[..complete].chunks_exact(BYTES_PER_LINE) {
                Base64::encode(chunk, &mut line_buf[..LINE_WIDTH])
                    .map_err(|_| io::Error::other("base64 encode"))?;
                self.inner.write_all(&line_buf)?;
            }
            self.buf.drain(..complete);
        }
        Ok(data.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        self.inner.flush()
    }
}

// ── Reader ────────────────────────────────────────────────────────────────────

/// Decodes a Cryptyrust PEM file line by line, streaming binary bytes to the caller.
pub struct PemReader {
    inner: io::BufReader<File>,
    decoded: Vec<u8>,
    pos: usize,
    done: bool,
}

impl PemReader {
    pub fn new(path: &Path) -> io::Result<Self> {
        let mut reader = io::BufReader::new(File::open(path)?);
        // Seek past the BEGIN line
        loop {
            let mut line = String::new();
            if reader.read_line(&mut line)? == 0 {
                break;
            }
            if line.trim().starts_with("-----BEGIN") {
                break;
            }
        }
        Ok(Self {
            inner: reader,
            decoded: Vec::new(),
            pos: 0,
            done: false,
        })
    }

    fn refill(&mut self) -> io::Result<()> {
        self.decoded.clear();
        self.pos = 0;
        while self.decoded.is_empty() && !self.done {
            let mut line = String::new();
            if self.inner.read_line(&mut line)? == 0 {
                self.done = true;
                return Ok(());
            }
            let trimmed = line.trim();
            if trimmed.starts_with("-----END") {
                self.done = true;
                return Ok(());
            }
            if trimmed.is_empty() {
                continue;
            }
            self.decoded = Base64::decode_vec(trimmed)
                .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, format!("{:?}", e)))?;
        }
        Ok(())
    }
}

impl Read for PemReader {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        if self.pos >= self.decoded.len() {
            if self.done {
                return Ok(0);
            }
            self.refill()?;
            if self.decoded.is_empty() {
                return Ok(0);
            }
        }
        let n = buf.len().min(self.decoded.len() - self.pos);
        buf[..n].copy_from_slice(&self.decoded[self.pos..self.pos + n]);
        self.pos += n;
        Ok(n)
    }
}

// ── Detection ─────────────────────────────────────────────────────────────────

pub fn is_pem_cryptyrust_file(path: &Path) -> bool {
    let Ok(f) = File::open(path) else {
        return false;
    };
    let mut reader = io::BufReader::new(f);
    let expected = format!("-----BEGIN {}-----", PEM_LABEL);
    for _ in 0..5 {
        let mut line = String::new();
        if reader.read_line(&mut line).unwrap_or(0) == 0 {
            break;
        }
        if line.trim() == expected {
            return true;
        }
    }
    false
}
