#ifndef CRYPTYRUST_H
#define CRYPTYRUST_H

/* Auto-generated by cbindgen — do not edit manually */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Operation succeeded.
 */
#define ARSENIC_OK 0

/**
 * Wrong password, corrupted data, or AEAD authentication failure.
 */
#define ARSENIC_ERR_DECRYPT -1

/**
 * I/O error (file not found, permission denied, etc.).
 */
#define ARSENIC_ERR_IO -2

/**
 * Invalid parameter (unknown cipher ID, unknown strength value, etc.).
 */
#define ARSENIC_ERR_PARAMS -3

/**
 * File does not carry the Arsenic V1 magic bytes or has a bad version.
 */
#define ARSENIC_ERR_BAD_MAGIC -4

/**
 * A required pointer argument was null.
 */
#define ARSENIC_ERR_NULL_PTR -5

/**
 * Unclassified error — call `arsenic_last_error()` for details.
 */
#define ARSENIC_ERR_UNKNOWN -99

/**
 * Heap-allocated byte buffer returned by `arsenic_encrypt` / `arsenic_decrypt`.
 *
 * **Must** be released with `arsenic_free_buffer` exactly once.
 * `ptr` is null and `len` is 0 when the associated call returned an error.
 */
typedef struct ArsBuffer {
    /**
     * Pointer to the data bytes (owned by Rust, do not free directly).
     */
    uint8_t *ptr;
    /**
     * Number of valid bytes starting at `ptr`.
     */
    uintptr_t len;
} ArsBuffer;

/**
 * Encryption parameters.
 *
 * **Cipher IDs** — same bytes as stored in the Arsenic V1 header:
 * - `0x02` Deoxys-II-256    (default header cipher)
 * - `0x03` XChaCha20-Poly1305 (default payload cipher)
 * - `0x04` AES-256-GCM-SIV
 *
 * **`strength`** — Argon2id cost preset:
 * - `0` Interactive  (256 MiB, ~1–3 s)
 * - `1` Sensitive    (1 GiB,  ~10–30 s)
 *
 * **`compress`** — payload compression:
 * - `0` disabled
 * - `1` zstd level 3 (per-block, before encryption)
 */
typedef struct ArsParams {
    uint8_t hdr_cipher;
    uint8_t pld_cipher;
    uint8_t strength;
    uint8_t compress;
} ArsParams;

/**
 * Optional progress callback.  `percentage` is in the range 0–100.
 * `user_data` is the value passed alongside the callback to the FFI function.
 * Pass null to ignore progress.
 */
typedef void (*ArsProgressFn)(int32_t percentage, void *user_data);

/**
 * Benchmark result for one AEAD cipher.
 */
typedef struct ArsBenchResult {
    /**
     * Cipher byte ID (matches `ArsParams.hdr_cipher` / `.pld_cipher`):
     * `0x02` Deoxys-II-256 · `0x03` XChaCha20-Poly1305 · `0x04` AES-256-GCM-SIV.
     */
    uint8_t cipher_id;
    /**
     * Encryption throughput in MiB/s.
     */
    double encrypt_mibps;
    /**
     * Decryption throughput in MiB/s.
     */
    double decrypt_mibps;
} ArsBenchResult;

/**
 * Array of benchmark results returned by `arsenic_bench`.
 *
 * Free with `arsenic_free_bench_array`.
 */
typedef struct ArsBenchArray {
    /**
     * Pointer to `count` results sorted fastest-first.
     */
    struct ArsBenchResult *results;
    /**
     * Number of elements in `results` (always 3 in the current implementation).
     */
    uintptr_t count;
} ArsBenchArray;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to the last error message (null-terminated, UTF-8).
 *
 * The pointer is valid until the next `arsenic_*` call on this thread.
 * Returns null if no error has occurred on this thread yet.
 */
const char *arsenic_last_error(void);

/**
 * Free a buffer previously returned by `arsenic_encrypt` or `arsenic_decrypt`.
 *
 * Passing a null pointer or a zeroed buffer is safe and has no effect.
 * Do **not** call this more than once on the same buffer.
 *
 * # Safety
 * `buf` must be null or point to a valid `ArsBuffer` produced by this library.
 */
void arsenic_free_buffer(struct ArsBuffer *buf);

/**
 * Returns default parameters:
 * Deoxys-II-256 header · XChaCha20-Poly1305 payload · Interactive · no compression.
 */
struct ArsParams arsenic_default_params(void);

/**
 * Encrypt a plaintext buffer in memory.
 *
 * On success writes the ciphertext to `*out` (caller must free with
 * `arsenic_free_buffer`) and returns `ARSENIC_OK`.
 * On failure returns a negative error code; `*out` is zeroed;
 * call `arsenic_last_error()` for a human-readable description.
 *
 * `progress_fn` / `user_data`: optional progress callback (pass null to ignore).
 *
 * # Safety
 * - `plaintext` must point to at least `plaintext_len` readable bytes.
 * - `password` and `params` must be valid non-null pointers.
 * - `out` must be a valid non-null pointer to an `ArsBuffer` the caller owns.
 */
int32_t arsenic_encrypt(const uint8_t *plaintext,
                        uintptr_t plaintext_len,
                        const char *password,
                        const struct ArsParams *params,
                        ArsProgressFn progress_fn,
                        void *user_data,
                        struct ArsBuffer *out);

/**
 * Decrypt a ciphertext buffer in memory.
 *
 * On success writes the plaintext to `*out` (caller must free with
 * `arsenic_free_buffer`) and returns `ARSENIC_OK`.
 * Cipher parameters are read from the file header — no `ArsParams` needed.
 *
 * # Safety
 * - `ciphertext` must point to at least `ciphertext_len` readable bytes.
 * - `password` must be a valid non-null pointer to a null-terminated string.
 * - `out` must be a valid non-null pointer to an `ArsBuffer` the caller owns.
 */
int32_t arsenic_decrypt(const uint8_t *ciphertext,
                        uintptr_t ciphertext_len,
                        const char *password,
                        ArsProgressFn progress_fn,
                        void *user_data,
                        struct ArsBuffer *out);

/**
 * Change the password of an Arsenic V1 file in-place.
 *
 * Returns `ARSENIC_OK` on success.
 * A crash-safe `.bak` backup is written before the in-place write and removed
 * on success (see FORMAT.md §7 for the full crash-recovery protocol).
 *
 * # Safety
 * All pointer arguments must be valid null-terminated C strings.
 */
int32_t arsenic_rekey_file(const char *path,
                           const char *old_password,
                           const char *new_password,
                           ArsProgressFn progress_fn,
                           void *user_data);

/**
 * Returns `1` if the file at `path` begins with the Arsenic V1 magic bytes,
 * `0` otherwise (including on error or null pointer).
 *
 * # Safety
 * `path` must be a valid null-terminated C string, or null.
 */
int32_t arsenic_is_arsenic_file(const char *path);

/**
 * Benchmark the three AEAD ciphers on `payload_mib` MiB of synthetic data
 * using a single Interactive Argon2id key derivation.
 *
 * Returns an `ArsBenchArray` sorted fastest-first.
 * The caller must free it with `arsenic_free_bench_array`.
 *
 * **Why only payload cipher?**
 * The header cipher encrypts only 32 bytes (the DEK), which takes nanoseconds
 * regardless of algorithm — its choice has no measurable effect on throughput.
 * Only the payload cipher (which processes the entire file) determines speed.
 * The benchmark therefore ranks payload ciphers; `arsenic_bench_best_combo`
 * recommends the same fastest cipher for both roles.
 *
 * `payload_mib = 32` is a good default (fast, stable results).
 */
struct ArsBenchArray arsenic_bench(uintptr_t payload_mib);

/**
 * Free an `ArsBenchArray` returned by `arsenic_bench`.
 *
 * # Safety
 * `arr` must have been returned by `arsenic_bench` and not yet freed.
 */
void arsenic_free_bench_array(struct ArsBenchArray arr);

/**
 * Write the recommended (hdr_cipher_id, pld_cipher_id) from a bench array to
 * `*hdr_out` and `*pld_out`.
 *
 * The array must be sorted fastest-first (as returned by `arsenic_bench`).
 * Both outputs are set to the fastest cipher found (index 0).
 *
 * # Safety
 * `arr.results` must point to `arr.count` valid `ArsBenchResult` values.
 * `hdr_out` and `pld_out` must be valid non-null pointers.
 */
void arsenic_bench_best_combo(const struct ArsBenchArray *arr, uint8_t *hdr_out, uint8_t *pld_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CRYPTYRUST_H */
