[package]
name = "cryptyrust_cli"
version = "1.0.1"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
description = "A simple but strong file encryption utility in Rust."
repository = "https://github.com/Antidote1911/cryptyrust/"
edition = "2021"

[dependencies]
cryptyrust_core = { path = "../core" }
rpassword = "5.0.1"
clap = { version = "3.1.3", features = ["cargo"] }
const_format = "0.2.22"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"

[[bin]]
name = "cryptyrust_cli"
