[package]
name = "cryptyrust_cli"
version = "1.0.0"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2018"

[dependencies]
cryptyrust_core = { path = "../core" }
rpassword = "5.0"
clap = "2"

[dev-dependencies]
assert_cmd = "1"
assert_fs = "1"

[[bin]]
name = "cryptyrust_cli"

[profile.release]
lto = true  
