[package]
name = "cryptyrust_core"
version = "2.5.0"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[dependencies]
argon2 = "0.4.0"
aead = { version = "0.4.3", features = ["std", "stream"] }
aes-gcm = "0.9.4"
aes-gcm-siv = "0.10.3"
chacha20poly1305 = "0.9.0"
deoxys = "0.0.2"
sha3 = "0.10.1"
blake3 = "1.3.1"
rand = "0.8.5"
thiserror = "1.0.30"
indicatif = "0.17.0-rc.11"
zeroize = "1.3.0"

[dev-dependencies]
rand = "0.8.5"
