[package]
name = "cryptyrust_core"
version = "1.0.4"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[dependencies]
argon2 = "0.4.0"
crypto_secretstream = "0.0.1"
rand_core  = "0.6.3"
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
hex = "0.4.3"

[dev-dependencies]
rand = "0.8.5"
