[package]
name = "cryptyrust_core"
version = "1.0.4"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[dependencies]
argon2 = "0.4.0"
aead = { version = "0.4.3", features = ["std", "stream"] }
aes-gcm-siv = "0.10.3"
rand = "0.8.5"
zeroize = "1.3"
bincode = "1.3.3"
hex = "0.4.3"
thiserror = "1.0.30"

[dev-dependencies]
rand = "0.8.5"
