[package]
name = "cryptyrust_core"
version = "2.0.0"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[dependencies]
argon2 = "0.4.0"
aead = { version = "0.4.3", features = ["std", "stream"] }
aes-gcm-siv = "0.11.0-pre"
chacha20poly1305 = "0.10.0-pre"
rand = "0.8.5"
secrecy = "0.8.0"
bincode = "1.3.3"
hex = "0.4.3"
thiserror = "1.0.31"
num_enum = "0.5.7"
anyhow = "1.0.57"

[dev-dependencies]
rand = "0.8.5"
