[package]
name = "cryptyrust_core"
version = "3.0.1"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[dependencies]
argon2 = "0.4.1"
aead = { version = "0.4.3", features = ["std", "stream"] }
aes-gcm = "0.9.4"
aes-gcm-siv = "0.10.3"
chacha20poly1305 = "0.9.1"
sha3 = "0.10.8"
blake3 = "1.5.1"
rand = "0.8.5"
thiserror = "1.0.61"
indicatif = "0.17.8"
zeroize = "1.3.0"

[dev-dependencies]
rand = "0.8.5"
