[package]
name = "cryptyrust_core"
version = "1.0.1"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2018"

[dependencies]
argon2 = "0.3.1"
scrypt = "0.8.0"
crypto_secretstream = "0.0.1"
rand_core = { version = "0.6", features = ["std"] }

[dev-dependencies]
rand = "0.8.5"
