[package]
name = "cryptyrust_core"
version = "1.0.2"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[dependencies]
argon2 = "0.3.1"
crypto_secretstream = "0.0.1"
rand_core  = "0.6.3"

[dev-dependencies]
rand = "0.8.5"
