[package]
name = "cryptyrust_adapter"
version = "1.0.4"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[lib]
name = "cryptyrust_adapter"
crate-type = ["staticlib"]

[dependencies]
cryptyrust_core = { path = "../core" }
zeroize = "1.3.0"
