name: ActionsCI

env:
  Platform: #Any CPU|Win32|x64
  Configuration: Release
  Artifacts: build/Release/

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build-windows-qt68:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17,18)'  # 17.xx
        msbuild-architecture: x64
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.8.1
        host:         windows
        target:       desktop
        modules:      qtmultimedia
        setup-python: false
        
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Build Rust project
      run: cargo build --release
      
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set CL=/MP
        cmake -B./build -S. ${{ github.workspace }}\qtgui
        cmake --build ./build --config ${{env.Configuration}}
        
    - name: deploy
      run:  |        
        windeployqt.exe --no-compiler-runtime --release build\Release\cryptyrust.exe
        
    - name: cleaning
      shell: cmd
      run:  |
        xcopy ${{ github.workspace }}\LICENSE build\Release
        xcopy ${{ github.workspace }}\target\release\cryptyrust_cli.exe build\Release
        rmdir /s /q build\Release\generic
        rmdir /s /q build\Release\networkinformation
        rmdir /s /q build\Release\iconengines
        rmdir /s /q build\Release\translations
        rmdir /s /q build\Release\imageformats
        rmdir /s /q build\Release\tls
        del /F build\Release\Qt6Network.dll
        del /F build\Release\Qt6Svg.dll
        del /F build\Release\D3Dcompiler_47.dll
        del /F build\Release\opengl32sw.dll
        
    - name: Compress artifacts
      uses: vimtor/action-zip@v1.1
      with:
        files: build\Release
        dest: "build/cryptyrust.zip"
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cryptyrust.zip
        path: build\Release
        
    - name: Calculate checksum
      run: |
        certutil -hashfile build/cryptyrust.zip SHA256 > build/cryptyrust.zip.sha256
        
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/cryptyrust.zip
        asset_name: cryptyrust_win_x64_${{ github.ref_name }}.zip
        asset_content_type: application/zip
        
    - name: Upload Checksum File
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/cryptyrust.zip.sha256
        asset_name: cryptyrust_win_x64_${{ github.ref_name }}.zip.sha256
        asset_content_type: text/plain


