name: Build Qt6 Application for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17,18)'  # 17.xx
        msbuild-architecture: x64

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        setup-python: false

    - name: Configure and Build
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        C:\Qt\6.2.2\msvc2019_64\bin\qmake.exe ..
        nmake

    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: Qt6App
        path: build/
